[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cmatch"
version = "0.1.0"
description = "CLI tool to match constraints using LLMs"
dependencies = [
    "requests",
    "python-dotenv",
    "termcolor",
    "psycopg2-binary",
    "pandas",
    "instances-api-client",
]

[project.scripts]
# Aqui acontece a mágica:
# "nome_do_comando = pasta.arquivo:função"
cmatch = "cmatch.main:main"
